import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("http://localhost:5000/login")
    page.locator(".d-flex").first.click()
    page.get_by_role("link", name=" Sign In").click()
    page.get_by_role("link", name=" Sign Up").click()
    page.get_by_role("link", name=" Sign In").click()
    page.get_by_role("heading", name="Sign-In").click()
    page.get_by_text("Access the dashboard panel").click()
    page.get_by_placeholder("Enter your email address").click()
    page.get_by_placeholder("Enter your email address").fill("admin@example.com")
    page.locator("form div").filter(has_text="Passcode").first.click()
    page.get_by_placeholder("Enter your passcode").click()
    page.get_by_placeholder("Enter your passcode").fill("123456")
    page.get_by_role("button", name="Sign in").click()
    page.get_by_role("heading", name="Admin Dashboard").click()
    page.get_by_role("link", name=" Dashboard").click()
    page.get_by_text("Today's Bookings").click()
    page.get_by_text("Total Rooms 4").click()
    page.get_by_text("Total Users 6").click()
    page.get_by_text("Bookings This Month 32").click()
    page.locator(".col-xxl-6 > .card > div").first.click()
    page.get_by_role("heading", name="Booking Trends").click()
    page.get_by_role("heading", name="Room Usage").click()
    page.get_by_text("Your Bookings Active Upcoming").click()
    page.get_by_text("Room Calendar Filter Rooms:").click()
    page.get_by_role("link", name="Upcoming").click()
    page.get_by_role("link", name="Past").click()
    page.get_by_role("link", name="Active").click()
    page.get_by_role("link", name=" Room Management").click()
    page.get_by_role("heading", name="Room Management").click()
    page.locator(".col-sm-6").first.click()
    page.locator("div:nth-child(2) > .card > .card-inner").click()
    page.get_by_role("button", name=" Add Room").click()
    page.get_by_role("textbox", name="Room Name").click()
    page.get_by_role("textbox", name="Room Name").fill("Testing")
    page.get_by_role("spinbutton", name="Capacity").click()
    page.get_by_role("spinbutton", name="Capacity").fill("100")
    page.get_by_role("textbox", name="Facilities").click()
    page.get_by_role("textbox", name="Facilities").fill("Testing")
    page.get_by_role("button", name="Save Room").click()
    page.get_by_role("button", name="Yes, add it!").click()
    page.get_by_role("button", name="OK").click()
    page.locator("div:nth-child(5) > .card > .card-inner").click()
    page.get_by_role("link", name=" User Management").click()
    page.get_by_role("heading", name="User Management").click()
    page.get_by_text("Name").click()
    page.get_by_text("Email").click()
    page.get_by_text("Role").click()
    page.get_by_text("Name Email Role Actions Devanshu Sonbhurra devanshu.sonbhurra@softude.com User").click()
    page.get_by_text("Devanshu Sonbhurra").click()
    page.get_by_text("devanshu.sonbhurra@softude.com").click()
    page.get_by_text("User", exact=True).first.click()
    page.get_by_text("User", exact=True).first.click()
    page.locator(".dropdown-toggle").first.click()
    page.get_by_role("button", name=" View Bookings").click()
    page.get_by_role("heading", name=" Devanshu Sonbhurra Bookings").click()
    page.locator("li").filter(has_text="Unknown RoomDate: Fri, 08 Nov 2024 00:00:00 GMTTime: 15:00 - 16:").click()

    print("All test cases is successfully passed.")

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
